<template>
    <div>
        <br>
        <v-layout justify-center><p style="font-size:44px; color:#61578b">Laser Tag Covenant</p></v-layout>
        <br>
        <v-layout justify-right><h1>Responsibilities and Expectations for Community Life at Taylor University</h1></v-layout>
        <br>
        <v-layout justify-right><h2 style="color:#007476">Introduction</h2></v-layout>
        <br>
        <div style="font-size:18px">
        <p>Taylor University is a community of Christians intentionally joined together for academic progress, personal development, and spiritual growth. The mission of Taylor University is to develop servant leaders marked with a passion to minister Christ’s redemptive love and truth to a world in need. Together we seek to honor Him by integrating biblical faith and learning while our hearts and lives embrace the process of maturing in Christ.</p>
        <p>The Taylor community consists of those who, in furtherance of our mission, are living together in intentional, voluntary fellowship, aware that we are called to live our lives before a watching world. Although primarily centered on the Upland campus, this community is not defined by geography, but rather by active engagement in the Taylor educational mission.</p>
        <p>The Life Together Covenant (LTC) identifies the expectations for living in community as we seek to fulfill our mission. It is impossible to create a community with expectations totally acceptable to every member. Nevertheless, certain responsibilities and expectations must be specified to assure orderly community life. When individuals join the Taylor community, they freely and willingly choose to take upon themselves the responsibilities and expectations outlined in this covenant. The University Expectations are not intended to measure spirituality or to promote legalism. Nevertheless, Galatians 5:13–14 reminds us that while we were called to be free, our freedom is best used when we serve one another in love. (Romans 14:1–23; 1 Corinthians 8:1–13, 10:23–33)</p>
        <p>A foundational support for the Life Together Covenant is the Taylor University Statement of Faith. The Statement of Faith affirms that the Bible is the inspired and authoritative word of God, and it provides the essential teachings and principles for personal and community conduct. The Statement of Faith also affirms the presence of the Holy Spirit in every believer; God, through the Holy Spirit, places in every believer the inner resources and attributes to minister to others through supportive relationships.</p>
        </div>
        <br>
        <v-layout justify-right><h2 style="color:#007476">Biblical Responsibilities</h2></v-layout>
        <br>
        <v-layout justify-right><h2 style="color:#61578b">Responsibilities for Loving God, Others, &amp; Self</h2></v-layout>
        <br>
        <div style="font-size:18px">

            <p>We glorify God by loving and obeying Him. Because we are commanded to love one another, relationships and behaviors which reflect such love confirm our allegiance to God and are glorifying to Him. (Matthew 22:36–40; John 15:11–14; Romans 15:5–6)</p>

            <p>Living in daily fellowship with other Christians is a privilege and an expression of God’s will and grace. In recognition of this privilege, great value is placed on the quality of relationships in our community. We acknowledge that we are living in a fellowship where we are dependent on and accountable to one another. The New Testament word for fellowship is koinonia, which is translated as a close mutual relationship, participation, sharing, partnership, contribution, or gift. Members, therefore, are encouraged to seek opportunities to demonstrate koinonia. (1 Corinthians 12:12–31; Ephesians 4:1–6)</p>

            <p>All persons are created in the image of God, and each person is known by God and knit together in the womb with intentional design. God’s attention to creative detail is uniquely applied in each person in whom is given the capacity to love God with heart, soul, mind, and strength. The commandment to love our neighbor as ourselves reminds us of our potential to minister to others while at the same time recognizing our own need for care and support. (Psalm 139:13–14; Mark 12:29–31; 1 Corinthians 6:19)</p>
        </div>
        <v-layout justify-right><h2 style="color:#61578b">Responsibilities for Community</h2></v-layout>
        <br>
        <div style="font-size:18px">
            <p>Within our community, the greatest expression of fellowship and the highest principle for relationships is love. Since God first loved us, we ought to demonstrate love toward one another. (1 John 3:11, 16, 18; 4:7–21) For the purpose of our community, we have identified the following specific expressions of love as being among the most desirable.</p>
            <p><span style="font-weight:bold">Building Up One Another</span>: We expect each member of the community to strive consciously to maintain relationships that support, encourage, and build up one another. (Romans 15:1–2)</p>
            <p><span style="font-weight:bold">Making Allowance for One Another</span>: Because of our fallenness, difficulties in relationships do occur. In such cases, we are to respond with compassion, kindness, humility, gentleness, and patience, making allowance for each other and forgiving one another. (Colossians 3:12–13)</p>
            <p><span style="font-weight:bold">Caring for One Another</span>: We are responsible to come alongside those experiencing grief, discouragement, illness, tragedy, or other personal trials. Expressions of bearing one another’s burdens include comfort, encouragement, consolation, and intercession. (Galatians 6:2)</p>
            <p><span style="font-weight:bold">Respecting One Another</span>: Because of the God-given worth and dignity of persons, each member of the community is expected to be sensitive to the image of God created in every person. Therefore, discrimination against others on the basis of race, national origin, age, gender, or disability is not acceptable. Any kind of demeaning gesture, symbol, communication, threat, or act of violence directed toward another person will not be tolerated. (Colossians 3:11–14; 1 John 3:14–18)</p>
            <p><span style="font-weight:bold">Speaking the Truth in Love</span>: A community such as ours can be strengthened by speaking the truth to each other with love. Problems in relationships and behavior can be resolved constructively by confronting one another in an appropriate spirit. If the welfare of the one being confronted is paramount and if the confronter is motivated by and acting in love, the process can produce growth. (Ephesians 4:15)</p>
            <p><span style="font-weight:bold">Reconciliation, Restoration, and Restitution</span>: Healing broken relationships is necessary for a healthy community. When relationships have been harmed, regardless of the reason, individuals are expected to reach out to one another, forgive one another, restore relationships, and make restitution. (Matthew 5:23–24; 18:15–17)</p>
        </div>
        <v-layout justify-right><h2 style="color:#61578b">Responsibilities for Individual Attitudes and Behavior</h2></v-layout>
        <br>
        <div style="font-size:18px">
            <p style="margin:0; padding:0"><span style="font-weight:bold">Attributes of the Heart</span>: Scripture gives us mandates for daily living through the Ten Commandments and the Sermon on the Mount. (Exodus 20:2–17; Matthew 5–7) In addition, Scripture teaches that certain attributes are available to individuals through the Holy Spirit. These attributes include: “love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, and self-control. Against such things there is no law.” (Galatians 5:22–24 NIV) This “fruit of the Spirit” is to be sought, encouraged, and demonstrated in our relationships. We are also called to live lives characterized by peace and holiness. (Hebrews 12:14)</p>
            <p>In contrast to encouraging these positive attributes of the heart, Scripture condemns injustice and attitudes such as greed, jealousy, pride, lust, prejudice, and hatred. Although these attitudes are sometimes difficult to discern, they can hinder relationships with God and others and lead to unacceptable behavior. (Galatians 5:19–21; Ephesians 4:31; Micah 6:8)</p>
            <p><span style="font-weight:bold">Prohibited Behaviors</span>: Certain behaviors are expressly prohibited in Scripture and therefore are to be avoided by all members of the community. They include theft, lying, dishonesty, gossip, slander, backbiting, profanity, vulgarity, crude language, sexual immorality (including adultery, homosexual behavior, premarital sex, and involvement with pornography in any form), drunkenness, immodesty of dress, and occult practice. (Mark 7:20–23; Romans 13:12–14; 1 Corinthians 6:9–11)</p>
            <p><span style="font-weight:bold">Academic Integrity and Truthfulness</span>: As a Christ-centered University community, we apply biblical responsibilities for honesty to all forms of academic integrity. Plagiarism is forbidden; we expect truthfulness and fidelity to be expressed in every learning context. (Luke 16:10; Ephesians 4:25)</p>
            <p><span style="font-weight:bold">Submission to Civil Authority</span>: In keeping with scriptural admonitions to bring ourselves under the authority of government, members of the Taylor community are expected to uphold the laws of the local community, the state, and the nation. An exception would be those rare occasions in which obedience to civil authorities would require behavior that conflicts with the teaching of Scripture. On such occasions, each individual would submit voluntarily to the penalty for his or her behavior. (Romans 13:1–7) Behavior resulting in arrest on or off campus is subject to review within the University’s disciplinary procedures.</p>
        </div>
        <br>
        <v-layout justify-right><h2 style="color:#007476">University Expectations</h2></v-layout>
        <br>
        <div style="font-size:18px">
            <p>In addition to subscribing to the section on Biblical Responsibilities, members of the Taylor University community voluntarily commit themselves to the following expectations of behavior. This commitment results from the conviction that these expectations serve the common good of the individual and the institution. These expectations are not set forth as an index of Christian spirituality, but rather as values and standards of the Taylor community and guidelines that serve to preserve the ethos of the campus community. Furthermore, they reflect our commitment to helping each member of the community grow in maturity and in the ability to make wise choices. Because of the importance of trust and responsibility to one another, violations of these expectations are regarded as a serious breach of integrity within the community. The following expectations apply to all members of the campus community: the faculty, staff, and students of Taylor University.</p>
            <p><span style="font-weight:bold">Worship</span>: Corporate worship, prayer, fellowship, and instruction are essential for our community. Therefore, students, faculty, and administrators are expected to attend chapel. Faithful participation is understood as a mature response to our community goals. We expect that individual honor and commitment to the Taylor community will motivate us to attend chapel. In addition, members of the community are encouraged to participate in the life of a local church.  </p>
            <p><span style="font-weight:bold">Lord’s Day</span> Members of the community are to observe this day as set apart primarily for worship, fellowship, ministry, and rest. While activities such as recreation, exercise, and study may be a part of the day, “business as usual” relative to University programs and services will not be sanctioned or encouraged.</p>
            <p><span style="font-weight:bold">Entertainment and Recreation</span> The University expects its members to use discretion and discernment in their choices of entertainment and recreation (some examples include media, Internet usage, and games). <span style="font-weight:bold">Each year, Student Development may sponsor a limited number of oncampus dances for the campus community. The University also considers the following forms of dance as acceptable for the campus community</span>: sanctioned folk dances, dances that are designed to worship God, dancing at weddings, and the use of <span style="font-weight:bold">appropriate</span> choreography in drama, musical productions, and athletic events. <span style="font-weight:bold">In order to preserve and enhance our intentional community</span>, other social dancing is not permitted on or away from campus. Activities and entertainment that are of questionable value or diminish a person’s moral sensitivity should be avoided. Consideration for others and standards of good taste are important, and all activities should be guided by this principle.</p>
            <p><span style="font-weight:bold">Illegal and Legal Substances</span>: Taylor University prohibits the possession, use, or distribution of illegal substances and the abuse or illegal use of legal substances, including prescription and over-the-counter medication.</p>
            <p><span style="font-weight:bold">Tobacco</span>: Recognizing that the use of tobacco is injurious to one’s physical health, members of the campus communities will not possess, use, or distribute tobacco in any form on or off campus. In addition, our campuses are smoke free.</p>
            <p><span style="font-weight:bold">Alcoholic Beverages</span>: The community recognizes the potential risk to one’s physical and psychological well-being in the use of alcoholic beverages. It also recognizes that use of alcoholic beverages can significantly and negatively impact the community. Accordingly, faculty, staff, and students will refrain from the use of alcoholic beverages. Alcoholic beverages are not served at any University functions or programs on or off campus.</p>
            <p><span style="font-weight:bold">Gambling</span>: Gambling (the exchange of money or goods by betting or wagering) is viewed as an unwise use of God-given resources and is not acceptable in any form.</p>
            <p><span style="font-weight:bold">Respect for the Property of Others</span>: Members of the community are expected to respect the property of others, including University property, private property on and off campus, and public property. The intellectual property of others is also to be respected.</p>
            <p><span style="font-weight:bold">Policies and Procedures</span>: Compliance with day-to-day policies and procedures of the community is expected from members. These routine items are listed in the Student Life Handbook, the Master Policy Manual, and the University catalog.</p>
        </div>
        <br>
        <v-layout justify-right><h2 style="color:#007476">Application</h2></v-layout>
        <br>
        <div style="font-size:18px">
            <p>The University affirms that the Biblical Responsibilities and University Expectations outlined herein lead to responsible citizenship and positive and healthy lifestyle, and they support the fulfillment of the University mission. While members of the community are encouraged to follow the principles of this LTC throughout the year, it is specifically applicable for students while they are actively engaged in the educational mission (Fall Semester, Interterm, Spring Semester, and Summer Term, including Thanksgiving, Christmas, and Spring Breaks) or are representing Taylor in any off-campus events. For employees, it is specifically applicable during the periods of their service or employment contracts.</p>
        </div>
        <br>
        <v-layout justify-right><h2 style="color:#007476">Conclusion</h2></v-layout>
        <br>
        <div style="font-size:18px">
            <p>The book of Colossians provides an appropriate summary of the goals for our community:</p>
            <blockquote style="margin-left:50px" cite=https://www.taylor.edu/life-together-covenant>“Therefore, as God’s chosen people, holy and dearly loved, clothe yourselves with compassion, kindness, humility, gentleness, and patience. Bear with each other and forgive one another if any of you has a grievance against someone. Forgive as the Lord forgave you. And over all these virtues put on love, which binds them all together in perfect unity. Let the peace of Christ rule in your hearts, since as members of one body you were called to peace. And be thankful. Let the message of Christ dwell among you richly as you teach and admonish one another . . . And whatever you do, whether in word or deed, do it all in the name of the Lord Jesus, giving thanks to God the Father through him.” (Colossians 3:12–17 TNIV)</blockquote>
            <br>
            <em>Approved by the Taylor University Board of Trustees 02/05/2013.</em>
        </div>
    </div>
</template>